package com.alichan.hostnavi.admin.infrastracture.model.custom;

import java.sql.Date;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ReservationReviewCustom {
  private Long id;
  private Long reservationId;
  private Long reservationInnId;
  private Long reservationInnUserId;
  private String reservationInnUserImageUrl;
  private String reservationInnUserName;
  private String reservationInnUserDescription;
  private String reservationInnUserAddress;
  private String reservationInnUserOccupation;
  private String reservationInnUserPhoneNumber;
  private String reservationInnUserMail;
  private Long reservationInnUserCreditCardId;
  private String reservationInnUserCreditCardNumber;
  private Date reservationInnUserCreditCardExpirationDate;
  private String reservationInnUserCreditCardCvv;
  private Date reservationInnUserCreditCardCreateTime;
  private Date reservationInnUserCreditCardUpdateTime;
  private String reservationInnUserFacebookUrl;
  private String reservationInnUserInstagramUrl;
  private String reservationInnUserTwitterUrl;
  private Date reservationInnUserCreateTime;
  private Date reservationInnUserUpdateTime;
  private String reservationInnName;
  private String reservationInnDescription;
  private Integer reservationInnFee;
  private Integer reservationInnStatusId;
  private String reservationInnStatusName;
  private Integer reservationInnTypeId;
  private String reservationInnTypeName;
  private String reservationInnAddress;
  private Integer reservationInnGuestNumber;
  private Integer reservationInnBedroomNumber;
  private Integer reservationInnBedNumber;
  private Integer reservationInnBathroomNumber;
  private Date reservationInnCreateTime;
  private Date reservationInnUpdateTime;
  private Integer reservationStatusId;
  private String reservationStatusName;
  private Long reservationReserverId;
  private String reservationReserverImageUrl;
  private String reservationReserverName;
  private String reservationReserverDescription;
  private String reservationReserverAddress;
  private String reservationReserverOccupation;
  private String reservationReserverPhoneNumber;
  private String reservationReserverMail;
  private Long reservationReserverCreditCardId;
  private String reservationReserverCreditCardNumber;
  private Date reservationReserverCreditCardExpirationDate;
  private String reservationReserverCreditCardCvv;
  private Date reservationReserverCreditCardCreateTime;
  private Date reservationReserverCreditCardUpdateTime;
  private String reservationReserverFacebookUrl;
  private String reservationReserverInstagramUrl;
  private String reservationReserverTwitterUrl;
  private Date reservationReserverCreateTime;
  private Date reservationReserverUpdateTime;
  private Date reservationCheckInTime;
  private Date reservationCheckOutTime;
  private Integer reservationGuestNumber;
  private Integer reservationFee;
  private Date reservationCreateTime;
  private Date reservationUpdateTime;
  private String review;
  private Integer cleanScore;
  private Integer serviceScore;
  private Integer facilityScore;
  private Integer locationScore;
  private Integer feeScore;
  private Date createTime;
  private Date updateTime;
}
