server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hostnavi?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  jackson:
    time-zone: Asia/Tokyo
  # swagger使用時、以下3行を記載しないとエラーが発生するため削除しないこと
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
    
testdb:
  url: jdbc:mysql://localhost:3306/hostnavi?allowPublicKeyRetrieval=true&useSSL=false
  user: root
  password: root

minio:
  endpoint: http://localhost:9000
  bucketName: image
  accessKey: alichan
  secretKey: alichan0609
